project_id = "staylink-local"

[api]
enabled = true
schemas = ["public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
major_version = 17

[storage]
enabled = true

[auth]
enabled = true
